### ISSUE TITLE
你好 请问一下你是怎么获取封面和歌曲的，下载下来 然后上传到github 然后通过cdn？

### ISSUE THREAD

**Issue by lone0x0** [woodwhales/woodwhales-music#4]
![截屏2021-09-28 08 44 45](https://user-images.githubusercontent.com/78702504/135004102-37c0cc3a-6131-4ac0-9f0a-2d762ce3d668.png
![截屏2021-09-28 08 45 25](https://user-images.githubusercontent.com/78702504/135004133-fc1b31b0-915f-4288-ae04-760da3e0bc67.png)
)

**Comment by woodwhales** [comment]
将你要下载的歌曲和封面上传到你自己创建的 github 公开仓库，注意创建不同的分支，每个分支大小不能超过 20 MB，在这个仓库对应的分支打 tag，访问：https://cdn.jsdelivr.net/gh/{你的github账号名称}/{你的github仓库名称}@{你的tag分支名称}/ 即可
